Repository agencyenterprise/react-native-health, pull requests merged in 2020-12, with the labels that each got.

#28 Add permission for AppleExerciseTime
  RCTAppleHealthKit/RCTAppleHealthKit+TypesAndPermissions.m
Labels: bug

#31 updated types to reflect results that present as Array
  index.d.ts
Labels: enhancement

#30 Documentation fixes
  README.md
Labels: documentation
