Repository agencyenterprise/react-native-health, pull requests merged in 2021-01, with the labels that each got.

#37 Export get and set body fat percentage methods
  RCTAppleHealthKit/RCTAppleHealthKit.m
Labels: bug

#29 Add KCal unit, standardize options for all Activity methods, export getAppleStandTime
  RCTAppleHealthKit/RCTAppleHealthKit+Methods_Activity.m
  RCTAppleHealthKit/RCTAppleHealthKit+Methods_Fitness.m
  RCTAppleHealthKit/RCTAppleHealthKit.m
  index.d.ts
  src/constants/Units.js
Labels: enhancement

#39 fix(getauthorizationstatus): fix getAuthorizationStatus failing
  RCTAppleHealthKit/RCTAppleHealthKit.m
  README.md
  docs/README.md
  docs/authorizationStatusForType.md
  docs/getAuthStatus.md
  index.d.ts
Labels: bug

#40 Update background.md
  docs/background.md
Labels: documentation
