Repository agencyenterprise/react-native-health, pull requests merged in 2021-03, with the labels that each got.

#47 Added ios14 activity types
  RCTAppleHealthKit/RCTAppleHealthKit+Utils.m
  index.d.ts
  src/constants/Activities.js
Labels: enhancement

#51 Added OxygenSaturation samples
  RCTAppleHealthKit/RCTAppleHealthKit+Methods_Vitals.h
  RCTAppleHealthKit/RCTAppleHealthKit+Methods_Vitals.m
  RCTAppleHealthKit/RCTAppleHealthKit+TypesAndPermissions.m
  RCTAppleHealthKit/RCTAppleHealthKit.m
  README.md
  docs/README.md
  docs/getOxygenSaturationSamples.md
  index.d.ts
  src/constants/Permissions.js
Labels: enhancement

#50 Save Workout add missing method
  RCTAppleHealthKit/RCTAppleHealthKit+TypesAndPermissions.m
  index.d.ts
Labels: bug

#56 docs: add saveWorkout documentation
  docs/saveWorkout.md
Labels: documentation

#54 docs: add docs to save blood alcohol/glucose
  docs/saveBloodAlcoholContent.md
  docs/saveBloodGlucoseSample.md
Labels: documentation

#65 fix: update return type to Array on Samples
  docs/getBloodAlcoholContentSamples.md
  docs/getBloodGlucoseSamples.md
  docs/getBloodPressureSamples.md
  docs/getBodyTemperatureSamples.md
  docs/getCarbohydratesSamples.md
  docs/getDailyDistanceSwimmingSamples.md
  docs/getHeartRateSamples.md
  docs/getHeartRateVariabilitySamples.md
  docs/getHeightSamples.md
  docs/getOxygenSaturationSamples.md
  docs/getRespiratoryRateSamples.md
  docs/getRestingHeartRateSamples.md
  docs/getSleepSamples.md
  docs/getVo2MaxSamples.md
  index.d.ts
Labels: enhancement
